//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Monopoly
{
	public abstract class Place
	{
        public String Name { get; set; }
        public int Price { get; set; }

        public abstract void Effect(Player p);
        public abstract int SellPrice();
        public abstract void Sold();

	}
}

